version: 0.0
os: linux
files:
  - source: todomvc
    destination: /opt/todomvc
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
      timeout: 600
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
      timeout: 300
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
      timeout: 300
